<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Cart;

class CartTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
          Cart::insert([
                [
                    'oitem' => '1',
                    'onum' => '1',
                    'oiid' => '4',
                    'iname' => 'ハンドバッグ',
                    'snum' => '1',
                    'picked' => '1',
                    'checked' => '0',
                    'sprice' => '40000',
                ],
                [
                    'oitem' => '2',
                    'onum' => '2',
                    'oiid' => '1',
                    'iname' => '白き恋人',
                    'snum' => '3',
                    'picked' => '1',
                    'checked' => '0',
                    'sprice' => '3000',
                ],
                [
                    'oitem' => '3',
                    'onum' => '2',
                    'oiid' => '6',
                    'iname' => 'カニ詰め合わせ',
                    'snum' => '1',
                    'picked' => '0',
                    'checked' => '0',
                    'sprice' => '25000',
                ],
                [
                    'oitem' => '4',
                    'onum' => '3',
                    'oiid' => '5',
                    'iname' => '兼松ハッカ',
                    'snum' => '10',
                    'picked' => '0',
                    'checked' => '0',
                    'sprice' => '8000',
                ],
                [
                    'oitem' => '5',
                    'onum' => '4',
                    'oiid' => '10',
                    'iname' => '木彫り熊',
                    'snum' => '1',
                    'picked' => '1',
                    'checked' => '1',
                    'sprice' => '8000',
                ],
                [
                    'oitem' => '6',
                    'onum' => '4',
                    'oiid' => '11',
                    'iname' => '生チーズケーキ',
                    'snum' => '1',
                    'picked' => '0',
                    'checked' => '0',
                    'sprice' => '3000',
                ],
                [
                    'oitem' => '7',
                    'onum' => '4',
                    'oiid' => '8',
                    'iname' => 'ご当地キャラのキーホルダー',
                    'snum' => '1',
                    'picked' => '0',
                    'checked' => '0',
                    'sprice' => '800',
                ],
                [
                    'oitem' => '8',
                    'onum' => '4',
                    'oiid' => '3',
                    'iname' => 'さっぽろの学校',
                    'snum' => '1',
                    'picked' => '0',
                    'checked' => '0',
                    'sprice' => '1000',
                ],
                [
                    'oitem' => '9',
                    'onum' => '5',
                    'oiid' => '9',
                    'iname' => 'アサヒカワビール',
                    'snum' => '3',
                    'picked' => '0',
                    'checked' => '0',
                    'sprice' => '6000',
                ],
                [
                    'oitem' => '10',
                    'onum' => '6',
                    'oiid' => '7',
                    'iname' => 'モッツァレラチーズ',
                    'snum' => '1',
                    'picked' => '0',
                    'checked' => '0',
                    'sprice' => '2000',
                ],
                [
                    'oitem' => '11',
                    'onum' => '6',
                    'oiid' => '2',
                    'iname' => '十勝銘菓あんばたーさん',
                    'snum' => '2',
                    'picked' => '0',
                    'checked' => '0',
                    'sprice' => '2200',
                ],
                [
                    'oitem' => '12',
                    'onum' => '6',
                    'oiid' => '3',
                    'iname' => 'さっぽろの学校',
                    'snum' => '1',
                    'picked' => '0',
                    'checked' => '0',
                    'sprice' => '1000',
                ],
                [
                    'oitem' => '13',
                    'onum' => '6',
                    'oiid' => '11',
                    'iname' => '生チーズケーキ',
                    'snum' => '1',
                    'picked' => '0',
                    'checked' => '0',
                    'sprice' => '3000',
                ],
                [
                    'oitem' => '14',
                    'onum' => '7',
                    'oiid' => '6',
                    'iname' => 'カニ詰め合わせ',
                    'snum' => '1',
                    'picked' => '0',
                    'checked' => '0',
                    'sprice' => '25000',
                ],
                [
                    'oitem' => '15',
                    'onum' => '7',
                    'oiid' => '12',
                    'iname' => '氷印の限定アイスクリーム',
                    'snum' => '2',
                    'picked' => '0',
                    'checked' => '0',
                    'sprice' => '6000',
                ],
                [
                    'oitem' => '16',
                    'onum' => '8',
                    'oiid' => '10',
                    'iname' => '木彫り熊',
                    'snum' => '1',
                    'picked' => '0',
                    'checked' => '0',
                    'sprice' => '8000',
                ],
                [
                'oitem' => '17',
                'onum' => '8',
                'oiid' => '5',
                'iname' => '兼松ハッカ',
                'snum' => '2',
                'picked' => '0',
                'checked' => '0',
                'sprice' => '1600',
                ],
                [
                'oitem' => '18',
                'onum' => '9',
                'oiid' => '3',
                'iname' => 'さっぽろの学校',
                'snum' => '2',
                'picked' => '0',
                'checked' => '0',
                'sprice' => '2000',
                ],
                [
                'oitem' => '19',
                'onum' => '9',
                'oiid' => '1',
                'iname' => '十勝銘菓あんばたーさん',
                'snum' => '2',
                'picked' => '0',
                'checked' => '0',
                'sprice' => '2200',
                ],
                [
                'oitem' => '20',
                'onum' => '9',
                'oiid' => '8',
                'iname' => 'ご当地キャラのキーホルダー',
                'snum' => '1',
                'picked' => '0',
                'checked' => '0',
                'sprice' => '800',
                ],

                ]);
        }
    }
